- README.md
- kube/public-site-deployment.yml
- src/common/config/index.js
- src/package.json
- src/server.js
Changes FE to use postgres as a session store
Need to test in SIT to confirm session functionality after upping replicaset.
> Change for using postgres as a session store

- kube/public-site-service.yml
Create ClamAV service for Performance Testing
It will allow Performance pod to access ClamAV REST API service available only to Public-Site up to now.
Network policy allowing such access will be deployed along with Performance testing pod to avoid any accidental Production deployment of such policy
N/A - deployment change
> Create ClamAV service for Performance Testing

- src/app/garfile/arrival/index.njk
- src/app/garfile/departure/index.njk
- src/common/templates/check-your-answers.njk
- src/locales/en.json
Field labels should not use abbreviations.
- change "Lat." to "Latitude" and "Long." to "Longitude"
> Externalise latitude and longitude labels to en.json

- src/app/garfile/arrival/index.njk
- src/app/garfile/arrival/post.controller.js
- src/app/garfile/craft/index.njk
- src/app/garfile/craft/post.controller.js
- src/app/garfile/departure/get.controller.js
- src/app/garfile/departure/index.njk
- src/app/garfile/departure/post.controller.js
- src/app/garfile/manifest/index.njk
- src/app/garfile/manifest/post.controller.js
- src/common/utils/validator.js
- src/test/garfile/arrival/post.controller.test.js
- src/test/garfile/craft/post.controller.test.js
- src/test/garfile/departure/get.controller.test.js
- src/test/garfile/departure/post.controller.test.js
- src/test/garfile/manifest/post.controller.test.js
- src/test/garfile/review/get.controller.test.js
- src/test/validators.test.js
If an arrival or departure port is set to ZZZZ, it is expected that co-ordinates are entered. However, the application and possibly CBP as well will raise an error if the port codes are the same, despite in this case potentially being different co-ordinates.
This is an initial attempt to address is by referring to departure ports in this instance to 'YYYY', in the hopes that this should pass app validations and possibly CBP as well.
This pull request also folds in a fix for SGAR-765, which addresses an issue where the GAR aircraft and manifest pages do not behave as expected due to having more than one action button.
PR process. If you are unable to mark off …
> SGAR-746 ZZZZ ports

- src/app/aircraft/add/index.njk
- src/app/garfile/craft/index.njk
- src/app/garfile/craft/post.controller.js
- src/common/templates/base-template.njk
- src/common/templates/includes/macros.njk
- src/test/garfile/craft/post.controller.test.js
Cleaned markup, added ids to hints and errors and the aria-describedby attributes.
Added the revised submission buttons.
Added javascript tweak to add buttonClicked field for the "Add to GAR" button, which may need applying for the manifest page.
Use of the updated form submissions will break the current E2E tests.
Initial pass of the aircraft screens, both saved and for GAR forms.
> Add screen reader tweaks to aircraft pages

- src/app/verify/get.controller.js
- src/locales/en.json
- src/test/verify/get.controller.test.js
This PR fixes an issue when the user verification link does not have a query/token provided in the URL which resulted in 'typeError- data must be string or buffer'. Now it handles the exception and displays a useful error message to the user.  
- [✅] Have you built the code locally and confirmed its working?
- [✅] Is the build confirmed to be passing on CI?
- [✅ ] Have you added enough relevant unit tests for your change?
- [✅] Have you added enough relevant E2E tests for your change?
- [✅ ] Have you updated any relevant documentation as part of …
> DSUP-3699 type error data must be string or buffer

- src/app/garfile/arrival/index.njk
- src/common/templates/includes/person-details.njk
time boxes now only accept the correct number of digits ie.e, 2 digits for month and 4 for year. Arrival details, Manifest persons (add, edit)
> added limit for date, month, year on arrival page, manifest person

- src/app/garfile/arrival/index.njk
- src/common/templates/includes/person-details.njk
added autotab to arrival, person manifest, when you add/edit person's date of birth and passport expiry date
the  pull request needs to go in before this. https://github.com/UKHomeOffice/egar-public-site-ui/pull/159
> Sgar 1095/autotab on all date input fields

- src/locales/en.json
Gars are now ordered by departure date when loaded. the pull requests adds the text on the main screen. 
> added text for gars are listed in order

- kube/public-site-deployment.yml
- src/app/unavailable/get.controller.js
- src/app/unavailable/index.njk
- src/common/config/availability.js
- src/common/config/index.js
- src/server.js
1. Updated wording of maintenance page with a toggle to switch between planned and unplanned outages. Planned outage displays start and end time of known maintenance window. 
2. Bugfix for nav bar showing incorrectly on unavailable page
3. Implemented a redirect to force users back to /welcome/index if they navigate to unavailable page when it is not enabled.
- [Y] Have you built the code locally and confirmed its working?
- [Y] Is the build confirmed to be passing on CI?
- [Y] Have you added enough relevant unit tests for your change?
- [Y] Have …
> DSUP-545 update maintenance page

- src/common/utils/airport_codes.json
Reverted change to Coal Aston - only a single airfield there now. 
Will reinstate the other one when more info available.
> reverted change to Coal Aston

- src/common/utils/airport_codes.json
https://collaboration.homeoffice.gov.uk/jira/browse/BED-95
Added following to airport_codes.json:
- SCHOOL FARM / WEST DEAN (United Kingdom) (A349)**
- NORTH ELMHAM / NEW LANE FARM (United Kingdom) (E190)
> added airports: A349, E190 to airport_codes.json

- kube/public-site-deployment.yml
We are now using a separate deployment running ClamAV hence the removal of the 2 containers within pod.
> Feature/fair-98 ClamAV config changes

- src/app/api/uploadfile/index.js
ℹ️ When a single file, images.pdf (>8MB in size) was uploaded:
[images.pdf](https://github.com/UKHomeOffice/egar-public-site-ui/files/13675341/images.pdf)
✅ The correct error message was displayed at the top of the page:
> Bugfix/fair 283/err msg for uploading files >8 mb

- src/common/utils/transformers.js
- src/package.json
Fixes `TypeError` for excel upload error (see [ticket information](https://collaboration.homeoffice.gov.uk/jira/browse/FAIR-380))
- checks for typeof string before spliting string.
- This previously caused an error during validation if left on checked.
- It was a concidence that this occurred during UPT, there was nothing stopping this bug from occurring at another time.
- removed transient dependency on lodash, it was unnecessary for the code.
> sGAR ~ 2024.01.20 ~ FAIR 380, type error from garfile

- .drone.yml
- README.md
- ops/kube/public-site-external-ingress.yml
- ops/kube/public-site-external-tls.yml
- ops/kube/public-site-internal-ingress.yml
- ops/kube/public-site-internal-tls.yml
* Add permanent certificate file to the application, meaning that certificate should be consistent across environments.
* Also makes the `base_url` (internal urls) and `base_url_service` (external urls) clearer.
I will delete this [documentation though](https://collaboration.homeoffice.gov.uk/display/BF/sGAR%3Ainvalid+certificate+issue+-+possible+fix).
* Use [ACP docs instead](https://docs.acp.homeoffice.gov.uk/how-to/security/cert-manager/).
> Feature/fair 400 - add certificate configuration into the egar-public-site-ui

- src/app/api/uploadgar/validations.js
- src/app/garfile/responsibleperson/validations.js
- src/app/people/validations.js
- src/common/utils/validator.js
- src/test/validators.test.js
Messages have been updated.
- tested via e2e tests (see sibling request https://gitlab.digital.homeoffice.gov.uk/egar/e2e-test/-/merge_requests/227/diffs).
- To fix AMG error changed by apostrephes in `firstname`, `Surname`, `operatorAddress1`,  `operatorAddress2`,  `operatorAddress3`, `operatorFirstName`, `operatorSurname`. (https://homeofficedigital.slack.com/archives/C061V6CD1R7/p1707407677281629).
- https://collaboration.homeoffice.gov.uk/jira/browse/FAIR-408
> Feature/fair 408 ~ 2024.02.09 ~ apostephe changes

- src/app/welcome/index.njk
Removed old link from events page.
> updated events page

- src/common/utils/airport_codes.json
> Sturgate Airfield set to be British and not in Hungary

- src/common/models/Cookie.class.js
- src/common/templates/includes/location.njk
- src/common/templates/includes/macros.njk
- craftBase no longer truncated to 4 chars, 6 instead
- lat long values with trailing 0s no longer have those 0s truncated
- screen reader function does not display GAR submission reference with extra spaces
> Feature fair 487 v

- src/app/garfile/view/get.controller.js
- src/app/garfile/view/post.controller.js
- src/common/templates/check-your-answers.njk
This update aligns the manifest view page with updates to the edit page so that all travel document fields are in the 'Travel Document Details' section.
It also removes the Response Message column, if isJourneyUKInbound is false.
> Document fields all in Travel Document Details, Response Message column only for UK inbound journeys.

- src/common/models/Cookie.class.js
* https://collaboration.homeoffice.gov.uk/jira/browse/FAIR-528
Basically, if you submit the gar without a value in the IATA/ICAO section and with an invalid data, it sued ot default to teh longtitude section, now it defaults to the latitude section.
[
](url)
** Tests **
> sGAR ~ 2024.06.20 ~ minor bugs for the stuff.

- src/app/api/uploadgar/validations.js
- src/locales/en.json
This pull request fixes the latitude and longitude error text.
* FAIR 538, departure and arrival code error for ZZZZ or YYYY is not explicit and tells the users to add a altitude or longitude coordinates.
* this change updates the text to not say that.
> FAIR-538 ~ 2024.07.31 ~ updated the text for iata code error

- src/app/garfile/amg/checkin/pane.njk
- src/common/templates/check-your-answers.njk
The fix for the different statuses colours display on GAR Summary page and Passenger Checks page.
> NMSW-2691 - fixed the response code status issue

- src/app/home/index.njk
In this PR added fix to download template url issue.  replace existing url code with below URL:
https://assets.publishing.service.gov.uk/media/660fba8263b7f8001fde18e2/GAR_Template_Apr_2024_v6.6_SDS_.xlsx
https://jira.bics-collaboration.homeoffice.gov.uk/browse/NMSW-3033
> NMSW-3033 added download template link to fix the download issue

- src/common/utils/airport_codes.json
Updated Chişinău International Airport IATA code.
https://en.wikipedia.org/wiki/Chi%C8%99in%C4%83u_Eugen_Doga_International_Airport
> nmsw-3399: update Chişinău International Airport IATA code.
