UKHomeOffice/egar-public-site-ui

- src/app/api/uploadgar/index.js
- src/common/utils/excelParser.js
- src/test/excelParser.test.js
Adds functionality for excel parser to start parsing after an identifying cell is found. 
Needed for manifest passenger parsing
- [] Has this change been tested against the Acceptance Criteria?
> Add functionality for excel parser to parse from an identifier cell

- kube/public-site-deployment.yml
Adds kube config for user not registered email template id for ticket egar-666
> added public site deployment env for template id

- .drone.yml
> Build on Production deployment

- src/app/garfile/view/submitted.njk
Disallow changing submitted/cancelled GARs
> Disallow changing submitted/cancelled GARs

- src/app/api/uploadgar/index.js
- src/common/utils/excelParser.js
- src/common/utils/transformers.js
- src/test/excelParser.test.js
- src/test/transformers.test.js
Adds document type validation on excel upload
> Add manifest document type validation on excel upload

- src/app/garfile/craft/index.njk
- src/app/garfile/craft/post.controller.js
Updates the garfile page for adding aircraft to match the prototype, with the exception that radio buttons for add saved craft are used instead of checkboxes.
> updated gar craft page styling

- src/app/garfile/craft/index.njk
Changed the add aircraft to gar button name
> changed add to gar button name

- src/app/garfile/review/get.controller.js
- src/app/garfile/review/index.njk
- src/app/garfile/review/post.controller.js
- src/common/templates/check-your-answers.njk
Updates error messages on gar submission review page to match govuk style
> updated validation and error on review page

- src/app/user/login/index.njk
> EGAR-441 Sign In Page - Styling review

- .editorconfig
- README.md
- docker-compose.yml
Local dev environment
Please read README.md for details
N/A - no need to add any tests as there is no functionality change
N/A - no need to add any tests as there is no functionality change
N/A - only dev environment
> Create local dev environment

- src/app/garfile/manifest/bulkAdd.js
- src/app/garfile/manifest/deleteperson/get.controller.js
- src/app/garfile/manifest/index.njk
- src/app/garfile/manifest/post.controller.js
- src/common/templates/base-template.njk
- src/public/javascripts/table-multiselect.js
Update the manifest page to match the prototype
Add bulk addition of saved people to manifest
> Egar 600 manifest styling review

- kube/public-site-deployment.yml
> Bringing replicaset to 1 temporarily

- kube/public-site-deployment.yml
> Bring replicaset back to 3

- src/app/garfile/home/get.controller.js
- src/app/garfile/home/index.js
- src/app/garfile/home/index.njk
- src/app/garfile/home/post.controller.js
- src/common/seeddata/egar_create_gar_options.json
**Note:** 
- The text for the radio buttons appears to be populated from the back end so I was unable to change text of these.
- I don't have access to E2E and wouldn't know how to create anyhow
> Radio buttons changed to vertical layout and code style refactor

- src/app/aircraft/index.njk
Adds csrf token to aircraft page
> added csrf token to aircraft page

- src/app/user/register/post.controller.js
Add additional logging around registration
> Add additional logging around registration

- src/app/api/uploadgar/index.js
- src/app/api/uploadgar/validations.js
- src/app/garfile/garupload/get.controller.js
- src/common/utils/transformers.js
- src/common/utils/validator.js
- src/test/validators.test.js
Validate entire excel file on GAR upload 
Display to the user a summary of GAR errors on failure (without creating a 'bad' GAR)
Add additional validators
> Egar 686 validate before upload

- src/app/user/manageuserdetail/index.njk
- src/app/user/viewDetails/index.njk
- src/common/templates/includes/header-user.njk
Update account page to match prototype
> Update account page to match prototype

- docker-compose.yml
- kube/public-site-deployment.yml
Increase ClamAV REST API timeout
N/A - preparation for performance testing
N/A
> Increase ClamAV REST API timeout

- src/app/garfile/home/index.njk
- src/app/garfile/home/post.controller.js
- src/app/garfile/responsibleperson/get.controller.js
- src/app/garfile/responsibleperson/index.js
- src/app/garfile/responsibleperson/index.njk
- src/app/garfile/responsibleperson/post.controller.js
- src/app/garfile/responsibleperson/validations.js
- src/common/templates/check-your-answers.njk
- src/common/utils/validator.js
- src/server.js
- src/test/validators.test.js
> Squash and sign previous commits

- src/app/garfile/home/post.controller.js
Fixes bug that was creating gars at the garfile selection choice stage for garfile upload
> fixed garfile upload choice bug that was creating gars erroneously

- src/app/organisation/index.njk
Adds csrf check to organisation page
> added csrf token to org user page

- src/common/templates/includes/header-user.njk
Navbar change to match prototype
> Update navbar to match prototype

- src/app/garfile/arrival/index.njk
- src/app/garfile/cancel/index.njk
- src/app/garfile/craft/index.njk
- src/app/garfile/customs/index.njk
- src/app/garfile/manifest/addnewperson/index.njk
- src/app/garfile/manifest/editperson/index.njk
- src/app/garfile/manifest/index.njk
- src/app/garfile/responsibleperson/index.njk
- src/app/garfile/review/index.njk
- src/app/garfile/supportingdocuments/index.njk
- src/app/home/index.njk
Remove unneccessary back buttons
> Update back buttons to have consistent behaviour

- src/app/aircraft/add/index.njk
- src/app/aircraft/edit/index.njk
- src/app/aircraft/index.njk
- src/app/organisation/assignrole/index.njk
- src/app/organisation/create/index.njk
- src/app/organisation/createsuccess/index.njk
- src/app/organisation/editorganisation/index.njk
- src/app/organisation/invitesuccess/index.njk
- src/app/organisation/inviteusers/index.njk
- src/app/people/add/index.njk
- src/app/people/edit/index.njk
- src/app/people/index.njk
- src/app/user/login/index.njk
- src/app/user/register/index.njk
- src/app/user/regmsg/index.njk
- src/app/verify/mfa/index.njk
Convert back butons to breadcrumbs where needed
Correct back button location where needed
> Remove back buttons where needed

- src/app/welcome/index.njk
> Remove sidebar and breadcrumbs from service start page

- src/common/templates/base-template.njk
> Add privacy policy and help links to footer

- src/app/cookie/get.controller.js
- src/app/cookie/index.js
- src/app/cookie/index.njk
- src/app/router.js
- src/common/templates/base-template.njk
- src/public/javascripts/cookie-banner.js
> Nojira cookie policy

- kube/public-site-ingress-for-service.gov.uk.yml
Add missing annotation added manually to Production ingress
N/A
N/A
> Add missing annotation

- .drone.yml
- kube/public-site-ingress-internal-redirect-from-homeoffice.gov.uk.yml
- Add backend for redirect ingress
- Add timeout=6m for deployments
> Add backend for redirect ingress rule

- src/app/aircraft/add/index.njk
- src/app/aircraft/edit/index.njk
- src/app/aircraft/index.njk
- src/app/garfile/arrival/index.njk
- src/app/garfile/craft/index.njk
- src/app/garfile/departure/index.njk
- src/app/garfile/garupload/index.njk
- src/app/garfile/manifest/index.njk
- src/app/garfile/submit/success/index.njk
- src/app/garfile/supportingdocuments/index.njk
- src/app/people/add/index.njk
- src/app/people/edit/index.njk
- src/app/people/index.njk
- src/app/user/deleteAccount/index.njk
- src/app/welcome/index.njk
- src/common/seeddata/egar_visit_reason_options.json
> Grammar and content changes

- src/app/user/register/index.njk
> Update privacy policy link on registration page

- src/app/user/regmsg/index.njk
> Remove private beta reference text

- src/app/api/uploadgar/validations.js
- src/app/garfile/arrival/index.njk
- src/app/garfile/arrival/post.controller.js
- src/app/garfile/departure/index.njk
- src/app/garfile/departure/post.controller.js
- src/common/utils/validator.js
- src/test/validators.test.js
> Add validation for same arrival / departure ports

- src/app/user/login/index.js
- src/app/welcome/get.controller.js
- src/common/middleware/usercheck.js
Reverts UKHomeOffice/egar-public-site-ui#59
> Revert "Nojira/unavailable page"

- src/app/verify/get.controller.js
- src/app/verify/registeruser/index.njk
> Check validity of registration token and create new token if expired

- dummy_file
> For deployment validation with gpg signature.

- README.md
- kube/public-site-deployment.yml
- src/app/router.js
- src/app/verify/get.controller.js
- src/common/config/index.js
- src/server.js
> Nojira service unavailable

- src/app/api/uploadfile/index.js
- src/app/garfile/supportingdocuments/get.controller.js
- src/common/utils/validator.js
- src/package.json
- src/test/validators.test.js
> Add file mimetype check to file upload process

- src/app/aircraft/add/index.njk
- src/app/aircraft/add/post.controller.js
- src/app/aircraft/edit/post.controller.js
- src/app/aircraft/index.njk
- src/app/api/uploadgar/index.js
- src/app/api/uploadgar/validations.js
- src/app/garfile/arrival/index.njk
- src/app/garfile/arrival/post.controller.js
- src/app/garfile/craft/index.njk
- src/app/garfile/departure/index.njk
- src/app/garfile/departure/post.controller.js
- src/app/garfile/manifest/addnewperson/post.controller.js
- src/app/garfile/manifest/editperson/post.controller.js
- src/app/garfile/manifest/index.njk
- src/app/home/index.njk
- src/app/people/add/post.controller.js
- src/app/people/edit/post.controller.js
- src/common/templates/check-your-answers.njk
- src/common/templates/includes/person-details.njk
- src/common/utils/transformers.js
Grammar fixes, cast country and port codes to upper case
> Cast country codes and port codes to upper case

- src/common/templates/check-your-answers.njk
- to match the flow of the GAR completion process
> EGAR-714 Change GAR Summary page content order

- .drone.yml
- README.md
- kube/public-site-deployment.yml
- sonar-project.properties
- src/app/garfile/arrival/post.controller.js
- src/app/garfile/departure/post.controller.js
- src/app/garfile/responsibleperson/post.controller.js
- src/app/garfile/review/get.controller.js
- src/app/garfile/view/post.controller.js
- src/app/home/post.controller.js
- src/app/user/detailschanged/get.controller.js
- src/app/user/manageuserdetail/get.controller.js
- src/app/user/register/post.controller.js
- src/app/verify/get.controller.js
- src/app/verify/mfa/get.controller.js
- src/app/verify/mfa/post.controller.js
- src/common/models/Session.js
- src/common/models/UserSessions.js
- src/common/models/WhiteList.js
- src/common/services/clamavservice.js
- src/common/utils/validator.js
- src/start.js
- src/test/user/detailschanged/get.controller.test.js
- src/test/user/manageuserdetail/get.controller.test.js
Before, especially for local development, there was a manual step to create a "session" table to be used by the JavaScript session handling libraries. This is now an automated step when starting the server leveraging Sequelize with additional custom SQL commands to execute the same manual step.
> Create Session table automatically

- src/app/garfile/responsibleperson/validations.js
Add missing word in Given name error message when exceeding maximum length
> Missing word in Given name error message

- src/app/aircraft/get.controller.js
- src/app/api/uploadgar/validations.js
- src/app/garfile/customs/post.controller.js
- src/app/garfile/home/post.controller.js
- src/app/garfile/manifest/bulkAdd.js
- src/app/garfile/manifest/get.controller.js
- src/app/garfile/manifest/post.controller.js
- src/app/garfile/responsibleperson/post.controller.js
- src/app/garfile/supportingdocuments/get.controller.js
- src/app/home/post.controller.js
- src/common/services/craftApi.js
- src/common/utils/validator.js
- src/server.js
- src/test/garfile/customs/get.controller.test.js
- src/test/garfile/customs/post.controller.test.js
- src/test/garfile/home/get.controller.test.js
- src/test/garfile/home/post.controller.test.js
- src/test/garfile/manifest/bulkAdd.test.js
- src/test/garfile/manifest/editperson/get.controller.test.js
- src/test/garfile/manifest/editperson/post.controller.test.js
- src/test/garfile/manifest/get.controller.test.js
- src/test/garfile/manifest/post.controller.test.js
- src/test/garfile/responsibleperson/get.controller.test.js
- src/test/garfile/responsibleperson/post.controller.test.js
- src/test/garfile/supportingdocuments/get.controller.test.js
- src/test/home/post.controller.test.js
- src/test/user/detailschanged/get.controller.test.js
- src/test/validators.test.js
Added a validator to check country codes. This leverages the library used to populate the list for the autocomplete, so should be robust. This means uploading Excels will check for non-empty and for whether the country is valid.
> EGAR-522 excel parser

- src/common/services/whiteList.js
- src/test/whitelistModel.test.js
SIT still has white listing enabled, which fail because emails were still checked against case sensitivity.
> Add case insensitivity to whiteList module

- src/app/garfile/responsibleperson/index.njk
- src/app/garfile/responsibleperson/validations.js
- src/locales/en.json
Responsible person page
-"County" field changed to "Country"
-"Country" text input field has been changed to autocomplete
> Egar cdr8 country autocomplete

- src/app/garfile/arrival/index.njk
- src/app/garfile/craft/validations.js
- src/app/garfile/customs/index.njk
- src/app/garfile/customs/post.controller.js
- src/app/garfile/customs/validations.js
- src/common/config/index.js
- src/common/models/Cookie.class.js
- src/common/templates/check-your-answers.njk
- src/common/utils/validator.js
- src/locales/en.json
- src/server.js
- src/test/garfile/customs/post.controller.test.js
- src/test/validators.test.js
Changes to the customs page, adding a text-box for users to provide customs declaration details.
> EGAR-661 customs page customs declaration

- README.md
- src/app/garfile/craft/get.controller.js
- src/app/garfile/craft/index.njk
- src/app/garfile/craft/post.controller.js
- src/app/garfile/manifest/index.njk
- src/app/people/index.njk
- src/common/templates/includes/pagination.njk
- src/test/aircraft/get.controller.test.js
- src/test/garfile/craft/get.controller.test.js
- src/test/garfile/craft/post.controller.test.js
- src/test/garfile/customs/post.controller.test.js
Hides previous and next links if not needed, or the pagination if only a single page of aircrafts are available. The "Add to GAR" button is also hidden during the GAR forms for aircraft if there are no saved aircraft and thus nothing possible to add.
Also added pagination to GAR aircraft page and unit tests to support.
> EGAR-772 and EGAR-764: Tweaks from QAT

- src/app/garfile/arrival/index.njk
- src/app/garfile/craft/index.njk
- src/app/garfile/customs/index.njk
- src/app/garfile/departure/index.njk
- src/app/garfile/manifest/addnewperson/index.njk
- src/app/garfile/manifest/editperson/index.njk
- src/app/garfile/responsibleperson/index.njk
- src/app/garfile/supportingdocuments/index.njk
- src/app/user/register/index.njk
- src/common/templates/includes/person-details.njk
Attempt to unify the styling of page where paragraphs should be 2/3 of page width.
Additionally, set reasonable max width on text input fields. 
> Sgar 760 paragraphs should be two third width

- src/app/garfile/customs/post.controller.js
- src/app/garfile/customs/validations.js
- src/test/garfile/customs/post.controller.test.js
Customs declaration details input is mandatory if users answer 'Yes' for customs declaration.
> SGAR-806 Make declaration detail field mandatory if customs declaration is yes

- src/app/aircraft/add/index.njk
- src/app/aircraft/edit/index.njk
- src/app/garfile/arrival/index.njk
- src/app/garfile/craft/index.njk
- src/app/garfile/departure/index.njk
Additional field width changes
-port code
-craft registration
> SGAR-762-field_width_changes_v2

- src/app/garfile/arrival/index.js
- src/app/garfile/departure/index.js
- src/app/garfile/home/get.controller.js
- src/app/garfile/home/index.js
- src/app/garfile/home/index.njk
- src/app/garfile/home/post.controller.js
- src/app/home/index.njk
- src/app/user/login/index.njk
- src/app/user/login/post.controller.js
- src/app/user/register/index.njk
- src/app/user/regmsg/index.njk
- src/app/verify/mfa/index.njk
- src/app/verify/mfa/post.controller.js
- src/app/verify/registeruser/index.njk
- src/common/templates/includes/errors.njk
- src/common/templates/includes/macros.njk
- src/locales/en.json
- src/server.js
- src/test/garfile/home/get.controller.test.js
- src/test/garfile/home/post.controller.test.js
- src/test/user/login/post.controller.test.js
- src/test/verify/mfa/post.controller.test.js
Removed the role button for the sign in, as it really is just a link rather a button to submit something. Leaving the button styling as it is the positive action for their respective screens.
Added aria-describedby attributes to hopefully aid input text inputs.
Refactored some variables, like 'Username' to 'username'.
Removed the unobtrusive validation attributes in the registration screen, as it is not used.
Externalised the strings for the login and registration screens.
This may address the login/registration screen reader issues. No way to prove or disprove.
Some refactoring around the html form input names, "Username" replaced with "username" just to begin some sense of consistency.
The following need to be checked off as …
> Possible screen reader tweaks for login and registration

- src/app/garfile/customs/index.njk
- src/common/seeddata/egar_craft_eu_free_circulation_options.json
- src/common/seeddata/egar_prohibited_goods_options.json
- src/locales/en.json
Changes to labels and description on the customs page to make it more clear to end user.
> UI changes on the customs page

- src/app/garfile/cancel/post.controller.js
Oversight letting some code from another branch creep into this one. Should be removed and unit tests confirmed to be ok now.
> SGAR-997 Fix broken unit test

- kube/public-site-deployment.yml
> Disabled statsd metrics to eliminate connection refused 111 errors.

- src/common/utils/airport_codes.json
Potential fix for the e2e tests failing. This PR removes a line which contains some weird characters that are invisible in normal editors but picked up within a version control editor.
- [✅] Have you built the code locally and confirmed its working?
- [ ✅] Is the build confirmed to be passing on CI?
- [✅ ] Have you added enough relevant unit tests for your change?
- [✅ ] Have you added enough relevant E2E tests for your change?
- [✅ ] Have you updated any relevant documentation as part of this change?
- [✅ ] Has this change been tested against the …
> Remove line with invisible random characters

- src/public/robots.txt
It now has the robots.txt file added. It will hopefully be respected by the mauibot and stop scanning. we need to keep an eye on kibana to tell us the full truth.
The reason I say hopefully is because, out of all, one website claims that the mauibot does not respect the robots.txt file. if that is the case, another solution needs to be looked into. The only way to find out is to try it. Worst case scenario is that this change would not make any difference but we will find out if the mauibot has stopped scanning the public site.  
- [] Have you …
> Sgar 1155/prevent maui bot scanning public site

- kube/public-site-deployment.yml
> Dsup 4417 automatic db creds

- src/app/garfile/departure/index.njk
- src/common/utils/validator.js
the 1092 pull request needs to go in before this. https://github.com/UKHomeOffice/egar-public-site-ui/pull/156
implemented autotab for departure page
> Sgar 1094/implement autotab

- .vscode/launch.json
- src/app/api/uploadgar/post.controller.js
- src/common/utils/excelParser.js
this will fix the pod recycling issue with incorrect templates being uploaded.
The passenger limit of 2,000 has been added and crew limit of 100 has been added. 
Also added the vs code file to help debug for later on. if someone else sets it up, it makes their life a bit easier.   
> Dsup 4867/invalid gar template fix

- src/app/people/validations.js
- src/common/utils/validator.js
- src/test/validators.test.js
User stories DSUP-4868 and SGAR-1173 are addressed in this pull request
When adding a date, the date is now checked. the date of birth is now checked to be at least 01/01/1900 or after that. 
The document expiry date is checked as well to make sure, it's in future. 
Also unit tests added for my code changes. 
> Dsup 4868/gar invalid date

- src/app/home/index.njk
- src/app/welcome/index.njk
> Signed latest commit for all changes made

- build_and_push
- src/app/garfile/customs/get.controller.js
- src/app/garfile/customs/index.njk
- src/app/garfile/customs/post.controller.js
- src/app/garfile/customs/validations.js
- src/app/garfile/review/validations.js
- src/app/welcome/index.njk
- src/locales/en.json
> Modifications for the brexit for 1/1/2021.

- src/app/garfile/customs/get.controller.js
- src/app/garfile/customs/post.controller.js
- src/common/templates/check-your-answers.njk
> Sgar 1175 brexit changes bugfix

- set_drone_secrets.sh
> Added a dummy comment for triggering a build.

- .drone.yml
- src/locales/en.json
> Sgar 1175 brexit changes/further modifications

- .drone.yml
- build_and_push
- src/locales/en.json
> Change gar sort order text

- kube/public-site-deployment.yml
> Fixed indentation for in secretKeyRef

- src/common/utils/airport_codes.json
> Created a new branch for the new codes

- src/common/utils/airport_codes.json
> aligned indentations

- .drone.yml
> Changed the timeout for the deployment.

- src/app/garfile/manifest/addnewperson/index.njk
- src/app/garfile/manifest/editperson/index.njk
- src/app/garfile/manifest/index.njk
- src/app/people/index.njk
- src/app/welcome/index.njk
- src/common/seeddata/egar_saved_people_travel_document_type.json
- src/common/templates/includes/person-details.njk
> Fixed as per Sonali's review.

- kube/public-site-deployment.yml
- src/app/unavailable/get.controller.js
- src/app/unavailable/index.njk
- src/common/config/availability.js
- src/common/config/index.js
- src/server.js
What changes does this PR bring?
- Updated wording of maintenance page with a toggle to switch between planned and unplanned outages. Planned outage displays start and end time of known maintenance window.
- Bugfix for nav bar showing incorrectly on unavailable page
- Implemented a redirect to force users back to /welcome/index if they navigate to unavailable page when it is not enabled.
Definition of Done
[Y] Have you built the code locally and confirmed its working?
[Y] Is the build confirmed to be passing on CI?
[Y] Have you added enough relevant unit tests for your change?
[Y] Have you added enough …
> Hotfix/dsup 545 (#188)

- src/public/javascripts/cookie-banner.js
> adding logging

- src/public/javascripts/cookie-banner.js
Updated the cookie domain name in the delete cookie function
> updating domain name for cookie deletion

- src/app/user/regmsg/get.controller.js
- src/public/javascripts/cookie-banner.js
- updating domain name for cookie deletion
- fixed import issue with Nano ID
> cookie compliance

- src/common/templates/base-template.njk
> reverting change

- src/app/garfile/departure/index.njk
> removed typo in import statement

- src/app/api/uploadgar/post.controller.js
> Set page to redirect to Review page after gar upload

- src/app/api/uploadgar/post.controller.js
- src/app/api/uploadgar/validations.js
Fixed airport validation on upload GAR
> Fixed british airport validation on uploading of GAR

- src/app/aircraft/delete/get.controller.js
- src/app/api/uploadgar/post.controller.js
- src/app/api/uploadgar/validations.js
- src/common/utils/airport_codes.json
- src/locales/en.json
- src/public/javascripts/cookie-banner.js
Updated Reference data to match CBP's upcoming changes
Updated grammar to meet business ask
Added cookie google analytics ID for staging
> Reference data updated

- src/app/garfile/arrival/index.njk
- src/app/garfile/departure/index.njk
> removed airport-id2 entry from index.njk

- src/app/garfile/arrival/index.njk
- src/app/garfile/departure/index.njk
> modified "or" condition to "and" in index.njk file

- src/app/garfile/arrival/index.njk
- src/app/garfile/departure/index.njk
> added "or" condition in airport id & airport id2

- src/app/garfile/arrival/index.njk
- src/app/garfile/departure/index.njk
- src/import-codes.js
> edited index.njk and import-codes file

- src/common/utils/airport_codes.json
> amended airport_codes

- src/common/utils/airport_codes.json
> added missed entry in airport_codes

- src/app/api/uploadgar/post.controller.js
> amended post controller

- src/app/api/uploadgar/validations.js
- src/common/utils/airportValidation.js
> amended validations to include non-uk port validity when uploaded from template

- src/app/api/uploadgar/validations.js
> edited a comment on validations to kick off a build

- src/locales/en.json
> updated wording around seconds to 4 decimal places

- src/common/templates/includes/person-details.njk
> edited one final entry on People document number

- src/app/aircraft/index.njk
- src/app/garfile/craft/index.njk
- src/app/garfile/manifest/index.njk
- src/app/organisation/index.njk
- src/common/templates/check-your-answers.njk
- src/locales/en.json
- src/server.js
> Added Search/Sort functionality

- src/app/organisation/index.njk
> Organisation bug fix on sort

- src/app/organisation/delete/get.controller.js
- src/app/organisation/delete/index.js
- src/app/organisation/get.controller.js
- src/app/organisation/index.njk
- src/app/organisation/post.controller.js
- src/app/router.js
- src/common/config/endpoints.js
- src/common/services/organisationApi.js
- src/common/templates/includes/success-action.njk
> Added a delete user button/option in Organisation

- src/app/people/index.njk
- src/common/services/personApi.js
- src/locales/en.json
> added person added date under people

- .drone.yml
- src/common/services/personApi.js
> edited personapi & drone.yml files

- src/common/services/personApi.js
> removed createdDateTime entry from PersonApi

- .drone.yml
- src/app/people/index.njk
- src/locales/en.json
> re-added index.njk, en.jason and drone.yml to new branch

- src/app/people/index.njk
> re-edited index.njk to remove double entries

- .drone.yml
- src/app/api/uploadgar/validations.js
- src/app/garfile/supportingdocuments/index.njk
- src/common/templates/includes/head.njk
- src/common/utils/validator.js
- src/locales/en.json
> supporting document change, validation on template and drone update

- src/app/people/index.njk
> Removed old code

- src/app/garfile/customs/index.njk
> Generated new variable id's to fix test conflicts

- src/app/garfile/customs/index.njk
> Added flag to open links in new tab on customs page

- src/app/api/uploadgar/post.controller.js
- src/app/api/uploadgar/validations.js
- src/app/garfile/arrival/post.controller.js
- src/app/garfile/departure/post.controller.js
- src/app/garfile/manifest/addnewperson/post.controller.js
- src/app/garfile/manifest/editperson/post.controller.js
- src/app/garfile/manifest/post.controller.js
- src/app/people/add/post.controller.js
- src/app/people/edit/post.controller.js
- src/common/models/Cookie.class.js
- src/common/services/personApi.js
- src/common/templates/includes/person-details.njk
- src/common/utils/airport_codes.json
- src/common/utils/validator.js
- src/locales/en.json
- src/package.json
> Patching, frontend changes and validation updates

- src/app/garfile/arrival/post.controller.js
- src/app/garfile/departure/post.controller.js
> removed validation on 1 month ahead

- src/app/garfile/arrival/post.controller.js
- src/app/garfile/departure/post.controller.js
- src/package.json
> downgraded packages

- src/app/garfile/arrival/post.controller.js
- src/app/garfile/departure/post.controller.js
- src/common/utils/validator.js
- src/locales/en.json
> Commented out additional code

- src/app/garfile/manifest/index.njk
- src/app/garfile/review/validations.js
> Updated customs validation

- src/common/seeddata/fixed_based_operator_options.json
- src/locales/en.json
> Updated text as requested

- src/common/templates/includes/head.njk
- src/public/javascripts/cookie-banner.js
> Added Google analytics 4 changes

- src/common/templates/includes/head.njk
> Updated tracking flag

- src/app/garfile/arrival/post.controller.js
- src/app/garfile/departure/post.controller.js
- src/app/garfile/printmanifest/index.njk
- src/app/home/index.njk
- src/common/templates/check-your-answers.njk
> Addition of Lat/Long variable instead of port name

- README.md
- kube/public-site-deployment.yml
- src/app/garfile/arrival/post.controller.js
- src/app/garfile/departure/post.controller.js
- src/app/garfile/printmanifest/index.njk
- src/app/home/index.njk
- src/common/templates/check-your-answers.njk
- src/common/templates/includes/head.njk
- src/public/javascripts/cookie-banner.js
- src/server.js
> Sgar v11.1

- src/app/api/uploadgar/validations.js
added text to file upload date validation message to suggest to user they check date fields are formatted as dates
> date validation errrors suggest correct cell format

- src/common/config/endpoints.js
> BED-28 (Not able to delete a user from eGAR)

- src/common/config/endpoints.js
- [] Have you added enough relevant unit tests for your change?
- [x ] Have you added enough relevant E2E tests for your change?
> BED-28 Delete organisation user.

- src/locales/en.json
> BED-37[Create organisation success message is incorrect]

- .drone.yml
used a basic node image instead of the sonarqube one that was used for running unit tests before
> tried a different image

- src/common/utils/validator.js
- src/test/api/uploadgar/post.controller.test.js
Fixes a bug where if arrival port is supplied empty/null/undefined a null reference exception is thrown.
> fixed null reference exception when validating null port

- src/common/utils/airport_codes.json
- src/import-codes.js
Updated airport file 
Fixed script that generates airport file (although the updates to the airport file did not use the script - the datasource the script uses did not have the new airports).
> Bed 55 import codes

- src/app/garfile/customs/post.controller.js
- src/locales/en.json
> GAR ~ 2023.06.28 ~ post and en.json added in.

- docker-compose.yml
- src/app/garfile/customs/get.controller.js
- src/app/garfile/customs/index.njk
- src/app/garfile/customs/post.controller.js
- src/app/garfile/customs/validations.js
- src/common/models/Cookie.class.js
- src/common/seeddata/egar_continental_shelf_options.json
- src/common/templates/check-your-answers.njk
- src/locales/en.json
> reverted customs

- .drone.yml
- README.md
- kube/public-site-deployment.yml
- kube/public-site-ingress-for-service.gov.uk.yml
- kube/public-site-ingress.yml
- src/app/garfile/customs/get.controller.js
- src/app/garfile/customs/index.njk
- src/app/garfile/customs/post.controller.js
- src/app/garfile/customs/validations.js
- src/common/models/Cookie.class.js
- src/common/seeddata/egar_continental_shelf_options.json
- src/common/templates/check-your-answers.njk
- src/common/utils/airport_codes.json
- src/locales/en.json
> Rebase dev

- docker-compose.yml
- src/app/garfile/amg/departure/post.controller.js
rture for the confirmation route requires a blank [] --> it can not be equal to None
-->as it uses that [] to go through exceptiojn ids. Therefore the post.contorller.
enforces this. it would be unedefiend, not null as it is a property which would not exist, hence, undefined.
- confirmation route needs the following payload if all the gars are going to departure and not be exceptioned:
```json
{ "exceptions": [] }
```
It was sending something like the below, which caused an error:
```json
{ "exceptions": null }
```
> sGAR ~ 2023.09.14 ~ all departure route has been fixed when submitting to the api

- src/app/garfile/manifest/deleteperson/get.controller.js
- src/common/templates/check-your-answers.njk
> FAIR-119 (Submitted GAR is updated with different list of passengers)

- src/test/garfile/review/post.controller.test.js
- src/test/organisation/create/post.controller.test.js
- src/test/user/viewDetails/get.controller.test.js
fixed unit tests after organisation and craft changes
> fixed unit tests after organisation and craft changes

- src/app/home/get.controller.js
- src/app/home/index.njk
> removed completed tab from gar table on homepage

- ops/kube/public-site-cert.yml
- ops/kube/public-site-ingress-external.yml
- external url for access without ACP VPN
> added public ingress/url for dev site

- .drone.yml
> Feature/fair 149 - Drone updates for Test environment

- src/app/api/uploadgar/validations.js
> FAIR-319 (Validate special characters while uploading GAR using excel)

- src/app/garfile/arrival/index.njk
- src/app/garfile/departure/index.njk
- src/common/templates/check-your-answers.njk
- src/common/templates/includes/banners.njk
added some banners into arrivals/departures
> moved arrival / banner updates into master

- src/app/welcome/index.njk
removes first eventbrite event from homepage
> removed first eventbrite event from homepage

- src/app/accessibility/index.njk
- src/locales/en.json
> FAIR-366 Update Accessibility Statement

- src/app/garfile/responsibleperson/validations.js
- src/common/utils/validator.js
- src/test/validators.test.js
> Fair 376 Postcode validation mismatch between sGAR and AMG

- src/common/services/garApi.js
Fixes bug found in by e2e tests (merge request for that change), where :
* if you fetch a gar that does not exist, it is suppose to redirect the user to the dashboard.
* However, currently, it does not.
* Hence, if the gar id is not found, it leads to a filter method being called on it, which causes a TypeError.
The reason this occurs is that the UPT code added in the api functions causes an error if the body.items is undefined.
* Add logging for all endpoints regarding  a 400 bad request or other.
* That means that if we do receive a bad request, we will get an error with a greater depth.
PR process. If you are unable to mark off an item as complete, then …
> Feature/fair 387 - fixes navigation tests by adding in a check for bad/server error requests

- src/app/aircraft/index.njk
- src/app/garfile/craft/index.njk
- src/app/garfile/manifest/index.njk
- src/app/home/index.njk
- src/app/organisation/index.njk
- src/app/people/index.njk
- src/common/templates/base-template.njk
- Updated jquery from 1.x to 3.7.
- Remove places where jQuery was placed, as jQuery is already downloaded via the in the base-template.
> Feature/fair 382 ~ 2024.01.30 ~ jquery updated

- .drone.yml
> fair-175 adding vulnerability scan CRON

- src/app/welcome/index.njk
> removed expired event link

- src/app/api/uploadgar/validations.js
- src/app/garfile/responsibleperson/validations.js
- src/app/people/validations.js
> sGAR ~ 2024.02.09 ~ fair 408 validations for the application.

- src/app/organisation/exportusers/get.controller.js
- src/app/organisation/exportusers/index.js
- src/app/organisation/get.controller.js
- src/app/organisation/index.njk
- src/app/people/export/get.controller.js
- src/app/people/export/index.js
- src/app/people/index.njk
- src/app/router.js
- src/package.json
- src/test/organisation/exportusers/get.controller.test.js
- src/test/people/export/get.controller.test.js
- Added endpoint that exports people as CSV
- Added link/button to people homepage
[people-2024-03-12.csv](https://github.com/UKHomeOffice/egar-public-site-ui/files/14574641/people-2024-03-12.csv)
----------------
the below tasks were actually not requested and implemented by mistake, but I have left is as they seem potentially useful.
- Added endpoint that exports organisation users as CSV
- Added link/button to organisation homepage
- (fixed table layout in organisation homepage when no action link is visible)
[Henry-Organisation-users-2024-03-12.csv](https://github.com/UKHomeOffice/egar-public-site-ui/files/14573274/Henry-Organisation-users-2024-03-12.csv)
> added endpoint to export organisation users as csv

- src/app/garfile/arrival/index.njk
- src/app/garfile/departure/index.njk
🚨 **Henry observed the following Live issue error:**
-  ✅ I refactored the code which should resolve this error.
- [ ✅] Have you built the code locally and confirmed its working?
- [ ✅] Is the build confirmed to be passing on CI?
🧪 **Evidence of manual testing:**
> Refactored 'No' radio button validation to resolve live issues

- src/test/garfile/review/post.controller.test.js
* New validation rules to add in when garfile fails.
* handle the validation runs when submitting the review.
> sGAR ~ 2024.03.27 ~ fixed the united tests.

- src/app/help/index.njk
removed support phone number from help page
> removed GAR support phone number from help page

- src/common/services/organisationApi.js
Improved logging so that issues regarding the incident FAIR 462 are resolve quicker next time.
* SIbiling merge request in data-access-api (https://gitlab.digital.homeoffice.gov.uk/egar/data-access-api/-/merge_requests/255).
> sGAR ~ 2024.04.04 ~ organisation logs.

- src/common/utils/airport_codes.json
- [ x] Have you considered how this will be deployed in SIT/Staging/Production?
> FAIR-468 Dedupe MLA airfield

- docker-compose.yml
> sGAR ~ 2024.04.11 ~ changes.

- src/common/utils/airport_codes.json
Added Sakhir Air Base to airfield data.
> added Sakhir Air Base

- src/common/templates/includes/person-details.njk
- src/locales/en.json
Adds the help text to tell users to include middle names.
Images attached.
> sGAR ~ 2024.04.19 ~ help information is added.

- src/app/help/index.njk
spec:
new page: (I emailed this screenshot to Sonali and Varinder for confirmation. Have not heard back and not sure if I am expecting to)
> updated help page copy

- src/app/garfile/responsibleperson/index.njk
Missed the responsible person given name label.
https://collaboration.homeoffice.gov.uk/jira/browse/FAIR-490
> sGAR ~ 2024.04.25 ~ missed responsible person.

- src/app/garfile/manifest/index.njk
- Bug fix for loose invalid text when invalid saved people section.
> sGAR ~ 2024.05.02 ~ invalid people is avaialble.

- src/locales/en.json
> changed Given name to Given names

- src/locales/en.json
> updated field_given_name_hint

- src/common/utils/airport_codes.json
> added Chavenay Aerodrome

- src/common/utils/airport_codes.json
> updated Berlin Airport

- src/common/templates/includes/person-details.njk
> added guidance to crew/passengers in add person to GAR and add saved person

- src/app/welcome/index.njk
> sGAR ~ 2024.05.08 ~ event added.

- src/common/utils/airport_codes.json
> FAIR-510 (add airport code Saint-Ghislain Airport (EBSG))

- src/app/people/validations.js
- src/test/people/edit/post.controller.test.js
Other document type had separate validations to the people sections for seemingly no reason.
> sGAR ~ 2024.05.19 ~ other validations are incorrect

- src/common/utils/airportValidation.js
> FAIR-520 (ICAO OR IATA CODE OF DEPARTURE PORT value ZZZZ throws error)

- ops/kube/public-site-deployment.yml
- src/app/welcome/get.controller.js
- src/app/welcome/index.njk
- src/common/config/index.js
- src/package.json
> FAIR-524 Temporary Home Page Notice

- src/common/utils/airport_codes.json
> FAIR-532 Add Sphinx Airport to List

- .drone.yml
> FAIR-534 removed the target attribute from CRON Scanning - drone file

- src/common/utils/airport_codes.json
> FAIR-535 - added KTYQ aircraft in the list

- src/package.json
> FAIR-320 added fix to public ui vulnerabilities

- src/app/welcome/index.njk
- Deleted and updated the copy on the homepage Events tab.
- [✅] Have you built the code locally and confirmed its working?
- [✅] Is the build confirmed to be passing on CI?
- [❌] Have you added enough relevant unit tests for your change?
- [❌] Have you added enough relevant E2E tests for your change?
- [❌] Have you updated any relevant documentation as part of this change?
- [✅] Has this change been tested against the Acceptance Criteria?
- [❌] Have you considered how this will be deployed in SIT/Staging/Production?
> Updated Events copy on the homepage

- src/app/garfile/resperson/index.njk
- src/app/resperson/add/index.njk
- src/app/resperson/edit/index.njk
- src/app/resperson/validations.js
- src/common/models/Cookie.class.js
- src/common/seeddata/egar_gar_dummy_data.json
- src/common/services/garApi.js
- src/common/templates/includes/responsible-person-details.njk
- src/common/utils/utils.js
- src/test/common/services/resPersonApi.test.js
- src/test/resperson/add/post.controller.test.js
- src/test/resperson/edit/get.controller.test.js
- src/test/resperson/edit/post.controller.test.js
- src/test/resperson/get.controller.test.js
- src/test/responsibleperson.test.js
```
ACCEPTANCE CRITERIA
- [✅] egar-public-site-ui: Change `responsibleCounty` to `responsibleCountry`.
```
Ticket details: [FAIR-105](https://collaboration.homeoffice.gov.uk/jira/browse/FAIR-105)
The form worked as expected after my updates:
- N/A
> Minor refactoring

- src/app/organisation/editusers/get.controller.js
- src/app/organisation/exportusers/get.controller.js
- src/app/organisation/get.controller.js
- src/app/organisation/index.njk
- src/app/organisation/post.controller.js
- src/app/organisation/searchusers/get.controller.js
- src/app/organisation/searchusers/index.js
- src/app/router.js
- src/common/config/endpoints.js
- src/common/services/organisationApi.js
- src/public/javascripts/organisation.js
- src/public/stylesheets/custom.css
- src/test/common/services/organisationApi.test.js
- src/test/organisation/editusers/get.controller.test.js
- src/test/organisation/exportusers/get.controller.test.js
- src/test/organisation/get.controller.test.js
- src/test/organisation/post.controller.test.js
- src/test/organisation/searchusers/get.controller.test.js
> Fair 470 organisation users pagination

- src/app/organisation/get.controller.js
- src/app/organisation/index.njk
- src/app/organisation/post.controller.js
- src/app/organisation/searchusers/get.controller.js
- src/public/javascripts/organisation.js
- src/test/organisation/post.controller.test.js
- src/test/organisation/searchusers/get.controller.test.js
* Fixes the enter app bug, where if a user presses the enter key, it does not submit the form.
* Removed javascript due to leading to a see all users if enter blank.
> Fair 470 - bug fixes

- src/app/garfile/cancel/post.controller.js
- src/app/garfile/review/post.controller.js
- src/test/garfile/review/post.controller.test.js
- send checkin request for all items when submitting.
- exception send for all checkin messages, not just when checkin response is received.
- async is used due to making the unit tests understandable.
----
Passes e2e tests (local) and a manual test.
> Fair 593 - onbound gar and inbound gars sent dat to apprioprate systems.

- ops/dev_deploy_vars.sh
> Amend dev deployment to use not_prod number of replicas

- .drone.yml
> Fixing shell path typo

- src/common/utils/airport_codes.json
- src/common/utils/autocomplete.js
- src/package.json
Adds the following airport codes:
* CWF/KCWF (chennault airport).
* JHF/SBJH (sao paulo airport).
Removed the airport:
* EGCA coal aston airport.
Changes to nationalities:
- Viet Nam to become Vietnam
- Add -  GBD  British Overseas Territories Citizen
- Add - GBN British National (Overseas)
- Add - GBO British Overseas Citizen
> NMSW-2247 ~ 2024.09.17 ~ airport codes updated and custom nationalities added.

- src/common/utils/airport_codes.json
[NMSW-2318](https://jira.bics-collaboration.homeoffice.gov.uk/browse/NMSW-2318) (Sonali urgents changes, 2 codes needs to added and amend (X720 & X591))
> NMSW-2318 [Sonali urgents changes, 2 codes needs to added and amend]

- src/app/garfile/amg/checkin/pane.njk
- src/app/help/index.njk
> NMSW-2337(Update sGAR passenger UPT response)

- src/app/help/index.njk
> NMSW-2337 (bug fixes)

- src/app/garfile/amg/checkin/pane.njk
- src/app/help/index.njk
> NMSW-2528 (CR039 sGAR Border Force CSH Telephone Number Update)

- ops/kube/public-site-deployment.yml
Email organisation template added to the kubernetes section.
> NMSW-2426 ~ 2025.01.09 ~ delete organisation email template.

- src/common/utils/airport_codes.json
> NMSW-2720 ~ 2025.01.24 ~ TFU airport codes has been added.

- src/app/garfile/amg/checkin/pane.njk
Fixed the loading issue by showing 'Awaiting' message while receiving the response code from AMG 
> NMSW-2691 - fixed the loading issue by showing awaiting message while getting response code from amg

- src/app/garfile/amg/checkin/pane.njk
> NMSW-2691 fix the loading message

- src/app/garfile/amg/checkin/pane.njk
> NMSW-2691 fix the display status message issue

- src/app/garfile/amg/checkin/pane.njk
> added new status messages for passenger checks screen

- src/common/utils/airport_codes.json
Added new airport code in the FE dropdown list
> NMSW-2989 added new carrier code

- src/app/api/uploadgar/post.controller.js
- src/common/utils/excelParser.js
In this PR: fixed the bug that was causing the application to crash.  
> NMSW-3031 - fixed the issue of crashing application after the file upload

- src/app/garfile/amg/checkin/pane.njk
- src/common/config/endpoints.js
- src/common/services/garApi.js
- src/locales/en.json
- src/public/stylesheets/custom.css
- src/test/common/services/garApi.test.js
In this PR:
added new 0B content 
> Nmsw 3095 update 0B content

- src/common/config/index.js
- src/server.js
> fix-samesite-issue

- src/app/garfile/manifest/index.njk
- src/app/user/deleteAccount/deleteAccountConfirmation/index.njk
- src/app/user/deleteAccount/get.controller.js
- src/app/user/deleteAccount/index.njk
- src/app/user/deleteAccount/utils.js
- src/app/user/onelogin/partials/confirm_name.njk
- src/app/user/onelogin/partials/given_name.njk
- src/app/user/viewDetails/index.njk
- src/common/templates/base-template.njk
- src/public/stylesheets/custom.css
> NMSW-2910: Updated UI to match design

- src/app/user/manageuserdetail/index.njk
- src/app/user/manageuserdetail/post.controller.js
- src/app/user/onelogin/partials/given_name.njk
- src/app/user/onelogin/post.controller.js
- src/common/utils/validator.js
> feat: Add validation rules to form

- src/app/user/login/get.controller.js
- src/app/user/login/index.njk
- src/app/user/manageuserdetail/get.controller.js
- src/app/user/manageuserdetail/old_index.njk
- src/app/user/viewDetails/get.controller.js
- src/app/user/viewDetails/old_index.njk
- src/common/config/index.js
- src/test/user/detailschanged/get.controller.test.js
- src/test/user/manageuserdetail/get.controller.test.js
- src/test/user/viewDetails/get.controller.test.js
> feat: Make sure flag resolve to boolean

- src/app/garfile/amg/checkin/pane.njk
- src/public/stylesheets/custom.css
> NMSW-3095 - fixed the 0B content alignment issue

- ops/kube/public-site-deployment.yml
- src/app/organisation/inviteusers/post.controller.js
- src/app/organisation/inviteusers/userExistError.njk
- src/test/organisation/inviteusers/post.controller.test.js
- src/test/user/viewDetails/get.controller.test.js
Updated Error message:
Old error message
> Nmsw 3166 invite fail to individual user

- src/app/organisation/assignrole/post.controller.js
- src/app/user/login/get.controller.js
> feat: Add more validation logic

- src/app/user/login/_partials/index.njk
- src/app/user/login/get.controller.js
- added updated content on login page.
- added test flag to test the one login page on production before turn the ONE_LOGIN_SHOW_ONE_LOGIN flag on.
https://jira.bics-collaboration.homeoffice.gov.uk/browse/NMSW-3308
> Nmsw 3308 update login screen content

- src/app/error/inviteExpiredError.njk
- src/app/organisation/assignrole/post.controller.js
- src/app/verify/organisationinvite/get.controller.js
- src/common/services/verificationApi.js
- src/test/organisation/assignrole/post.controller.test.js
- src/test/verify/organisationinvite/get.controller.test.js
- added checks for invitation expiry link.
- added last name in the email
- added base url checks for not prod environment
> Nmsw 3158 add invite expiry link and lastname in invite email

- src/app/user/deleteAccount/post.controller.js
- src/app/user/login/post.controller.js
- src/app/user/logout/get.controller.js
> feat: redirect failing after delete

- src/app/organisation/inviteusers/validations.js
Added validation to check firstname, lastname and email on invite user form.
> Nmsw 3330 invite email form validation

- src/app/user/login/get.controller.js
> feat: Fix post migration

- src/app/user/login/get.controller.js
- Fixing errors when logging in with existing user
- Fixing redirect errors 
> Fix: Fixing redirect bugs during Onelogin

- src/app/user/login/get.controller.js
> NMSW-3355-fix-error-cases-for-onelogin-fix

- src/app/user/login/get.controller.js
> fix: add res.redirect

- src/app/user/login/get.controller.js
> fix-add-redirect-call-in-sendonelogin-cookieset

- src/app/organisation/assignrole/get.controller.js
- src/app/organisation/assignrole/index.js
- src/app/organisation/assignrole/index.njk
- src/app/organisation/assignrole/post.controller.js
- src/app/organisation/editusers/get.controller.js
- src/app/organisation/editusers/post.controller.js
- src/app/organisation/editusers/validations.js
- src/app/organisation/get.controller.js
- src/common/middleware/pageAccess.js
- src/common/utils/nav.js
- src/common/utils/permissionLevels.js
- src/test/organisation/assignrole/get.controller.test.js
- src/test/organisation/assignrole/post.controller.test.js
- src/test/organisation/editusers/post.controller.test.js
- Added the pageAccess to restrict the view of the pages for 'User' group.
> NMSW-3344- added restriction on access of pages for users

- src/package-lock.json
- src/package.json
Put back jwk-rsa library for onelogin
> fix: Put back jwk-rsa lib

- src/common/utils/airport_codes.json
[NMSW-2894](https://jira.bics-collaboration.homeoffice.gov.uk/browse/NMSW-2894)
- Adds [Luneberg Airport (Germany) (EDHG)](https://www.world-airport-codes.com/germany/luneburg-62565.html) to the airfields list.
[NMSW-3466](https://jira.bics-collaboration.homeoffice.gov.uk/browse/NMSW-3466)
- Adds [Manohar International Airport (India) (GOX / VOGA)](https://en.wikipedia.org/wiki/Manohar_International_Airport)
- Adds [Benfield Aerodrome (Ireland) (EIBF)](https://funfly.ie/benfield-aerodrome/)
- Adds Oil Rig/Offshore Installation (International Waters) (ZZZR)
- Updates ICAO code for [Gazipaşa Airport (Turkey)](https://en.wikipedia.org/wiki/Gazipa%C5%9Fa%E2%80%93Alanya_Airport) to LTFG
The following need to be checked off as they are …
> NMSW-2894 and 3466: Add or update 5 airfields

- src/app/garfile/amg/checkin/get.controller.js
- src/app/garfile/amg/checkin/index.js
- src/app/garfile/amg/checkin/index.njk
- src/app/garfile/amg/checkin/pane.njk
- src/app/garfile/amg/checkin/post.controller.js
- src/app/garfile/amg/checkin/resubmit.njk
- src/app/garfile/review/index.njk
- src/app/garfile/review/post.controller.js
- src/app/garfile/submit/success/index.njk
- src/app/garfile/view/get.controller.js
- src/app/garfile/view/post.controller.js
- src/app/organisation/index.njk
- src/common/config/endpoints.js
- src/common/services/garApi.js
- src/common/templates/base-template.njk
- src/common/templates/check-your-answers.njk
- src/common/templates/includes/macros.njk
- src/common/utils/utils.js
- src/locales/en.json
- src/public/javascripts/resubmitGar.js
- src/public/stylesheets/application.css
- src/public/stylesheets/custom.css
- src/test/common/services/garApi.test.js
- src/test/garfile/view/get.controller.test.js
- src/test/garfile/view/post.controller.test.js
**NMSW-3129 - display passengers with 0T**
**NMSW-3128 - resubmission of passengers with 0T**
**NMSW-3325 - update permissions to travel guidance**
NMSW-3462 - GAR summary page with 0T 
NMSW-3463 - GAR summary page resubmission button for 0T
NMSW-3461 - Confirmation screen content updates after GAR submission
NMSW-3464 - confirmation email content after GAR submitted successfully.
> Nmsw 3128 0T resubmission of passengers

- src/common/utils/pagination.js
- src/public/javascripts/resubmitGar.js
- src/test/common/utils/pagination.test.js
- there was an issue with resubmit url, fixed the issue in the PR.
- corrected pagination count
> fixed url issue

- src/common/services/organisationApi.js
Return error message appropriate when updating to existing name. 
> feat: Show error on editOrganisation when name exists

- src/app/garfile/review/post.controller.js
- src/common/services/garApi.js
refactored code for 0T resubmit. Removed unused code
> 0T refactored the code
